### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by YaNIND** [jibixyt/AntiInternalKick#2]
Hy you can create anti login timeout?

**Comment by J1b1x** [comment]
> Hy you can create anti login timeout?

Lemme see

**Comment by DerCooleVonDem** [comment]
Most of the times a login timeout is caused by your internet connection :)

**Comment by YaNIND** [comment]
> Most of the times a login timeout is caused by your internet connection :)

not connection is can timeout all players join to server
