### ISSUE TITLE
Anticonnexion

### ISSUE THREAD

**Issue by xodamcm** [jibixyt/AntiInternalKick#3]
Please rename this plugin: Anticonnexion i can’t connect myself 😂😂😂: Login Timeout

**Comment by J1b1x** [comment]
> Please rename this plugin: Anticonnexion i can’t connect myself 😂😂😂: Login Timeout

No xD

**Comment by J1b1x** [comment]
> Please rename this plugin: Anticonnexion i can’t connect myself 😂😂😂: Login Timeout

Okay i got this report from some peoples, can you please explain what exactly happens? Like if you upload the plugin ,restart the server and try to join you get kicked for login timeout?
