### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by chisi21** [jibixyt/AntiInternalKick#4]
Cant join? Login timeout

**Comment by DerCooleVonDem** [comment]
Thats your internet connection! :)

**Comment by chisi21** [comment]
> Thats your internet connection! :)

not only me, other players experienced the same thing after unfortunately installing this plugin

**Comment by J1b1x** [comment]
> Cant join? Login timeout

i dont had that bug yet, please explain what exactly happens?

**Comment by YaNIND** [comment]
@chisi21 maybe delete your players data

**Comment by J1b1x** [comment]
> @chisi21 maybe delete your players data

yeah, i mean its possible that that error will be prduced by this plugin, but ig its an internet or server problem

**Comment by ArasakaID** [comment]
its like the raklib is not registered correctly, you have to restart the server for many time to work

**Comment by DevGod6969** [comment]
Yea
